//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuocDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUOCTHUEBAO
    {
        public string IDcuoc { get; set; }
        public string Tencuoc { get; set; }
        public Nullable<System.TimeSpan> TGBD { get; set; }
        public Nullable<System.TimeSpan> TGKT { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<System.DateTime> Ngayapdung { get; set; }
    }
}
