//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuocDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINSIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINSIM()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.THOIGIANSUDUNGs = new HashSet<THOIGIANSUDUNG>();
        }
    
        public string IDSim { get; set; }
        public string IDKHACHHANG { get; set; }
        public string Sdt { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public Nullable<double> CuocDK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIGIANSUDUNG> THOIGIANSUDUNGs { get; set; }
    }
}
